#!/usr/bin/env csh

###################################################
#						  #
# USAGE: ./GEOSldas_nightlytest -e EMAIl -g TAG   #
#						  #
# This script runs Matt Thompson's LDAS_nighly	  #
#  test for user specified GEOSldas github tag.	  #
#						  #
# Arguments:					  #
#   -g Github tag name				  #
#   -e Users email address for summary   	  #
#             Sarith Mahanama and Weiyuan Jiang   #
#	                          (Mar 10, 2020)  #
###################################################

###################################################
# PROCESS COMMAND LINE AND GET EMAIL AND TAG NAME #
###################################################

if($#argv == 0) then
    echo "USAGE : ./GEOSldas_nightlytest -e EMAIl -g TAG "
    echo "   -g Github tag name"
    echo "   -e email address"
    echo "   -h this message"
    exit
endif


set arg_list=(`getopt -s tcsh -o hm:g:e: --long g-long,e-long: -- $argv:q`)

eval set argv=\($arg_list:q\)

while (1)
	switch($1:q)
	case -g:
	case --g-long:
		set GITTAG = $2 
                shift ; shift 
		breaksw
	case -e:
	case --e-long:
		set EMAIL = $2
                shift ; shift
		breaksw
	case -h:
                shift ; shift
		echo "-g Github tag name"
 		echo "-e email address"
                exit
 		breaksw
	case --:
		shift
		break
	default:
	        echo $2
		echo "Internal error!" ; exit 1
	endsw
end

if( $?GITTAG == 0 ) then
    echo "ERROR : GITHUB tag name is required " 
    ./GEOSldas_nightlytest
    exit
endif
if( $?EMAIL == 0 ) then
    echo "ERROR : Email address is required"
    ./GEOSldas_nightlytest
    exit
endif

###################################################
#       SET ENV VARIABLES AND CREATE DIRS         #
###################################################

setenv SYSTESTDIR /discover/nobackup/smahanam/GEOSldas_nightly/systest/
#setenv SYSTESTDIR /gpfsm/dhome/mathomp4/SI_Team/scripts/systest/
setenv CURRENTTAG $GITTAG
setenv MYEMAIL $EMAIL

###################################################
#          COPY INPUT FILES AND UPDATE            # 
###################################################

mkdir -p /discover/nobackup/$USER/GEOSldas_nightly/scripts/input/LDAS/
/bin/cp -p $SYSTESTDIR/* /discover/nobackup/$USER/GEOSldas_nightly/scripts/.

# WJ: At the momemnt CONUS only
/bin/cp -p $SYSTESTDIR/input/LDAS/conus.model.slurm /discover/nobackup/$USER/GEOSldas_nightly/scripts/input/LDAS/.

source g5_modules;
./read_GEOS_LandGridComp $SYSTESTDIR/input/LDAS/conus.model.exec /discover/nobackup/$USER/GEOSldas_nightly/scripts/input/LDAS/conus.model.exec

###################################################
#                RUN Matt's SCRIPTS               # 
###################################################

set PWD = `pwd`
cd /discover/nobackup/$USER/GEOSldas_nightly/scripts
nohup ./LDAS_Nightly_Cron.csh &

cd $PWD
/bin/rm git.exec





