name: "Build and Test GEOSldas"
description: "Build and test GEOSldas"

# Define the inputs for this action
inputs:
  fortran-compiler:
    description: "The Fortran compiler to use"
    required: true
  cmake-build-type:
    description: "The CMake build type"
    required: true
  cmake-generator:
    description: "The CMake generator to use"
    required: true
  extra-cmake-args:
    description: "Extra CMake arguments"
    required: false

runs:
  using: "composite"

  steps:
    # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
    - name: Delete huge unnecessary tools folder
      shell: bash
      run: rm -rf /opt/hostedtoolcache

    - name: Set all directories as git safe
      shell: bash
      run: |
        git config --global --add safe.directory '*'

    - name: Versions etc.
      shell: bash
      run: |
        ${{ inputs.fortran-compiler }} --version
        mpirun --version
        echo $BASEDIR

    - name: Mepo clone external repos
      shell: bash
      run: |
        mepo clone --partial blobless
        mepo status

    - name: Update other branches
      shell: bash
      if:
        "!contains('refs/heads/main,refs/heads/develop', github.ref)"
      run: |
        mepo checkout-if-exists ${GITHUB_HEAD_REF}
        mepo status

    - name: CMake
      shell: bash
      run: |
        cmake -B build -DCMAKE_Fortran_COMPILER=${{ inputs.fortran-compiler }} -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=${{ inputs.cmake-build-type }} -DUSE_F2PY=OFF -G "${{ inputs.cmake-generator }}" "${{ inputs.extra-cmake-args }}"

    - name: Build
      shell: bash
      run: |
        cmake --build build --parallel 4
        cmake --install build
